const theme = {
  color: 'white',
  colors: {
    primary: 'black',
    secondary: 'blue',
    fontColor: 'white',
  },
  typhography: {
    color: 'white',
    h1: {
      fontSize: '3.052rem',
      lineHeight: '1.3',
      fontWeight: '400',
      margin: '3rem 0 1.38rem',
    },
    h2: {
      fontSize: '2.441rem',
      lineHeight: '1.3',
      fontWeight: '400',
      margin: '3rem 0 1.38rem',
    },
    h3: {
      fontSize: '1.953rem',
      lineHeight: '1.3',
      fontWeight: '400',
      margin: '3rem 0 1.38rem',
    },
    h4: {
      fontSize: '1.563rem',
      lineHeight: '1.3',
      fontWeight: '400',
      margin: '3rem 0 1.38rem',
    },
    h5: {
      fontSize: '1.25rem',
      lineHeight: '1.3',
      fontWeight: '400',
      margin: '3rem 0 1.38rem',
    },
    small: { fontSize: ' 0.8rem' },
    paragraph: {
      fontSize: '1.266rem',
      lineHeight: '1.15',
      fontWeight: '300',
    },
  },
  button: {
    textColor: 'white',
    marginTop: '5px',
    display: 'inline-block',
    fontWeight: '400',
    textAlign: 'center',
    whiteSpace: 'nowrap',
    border: '1px solid transparent',
    padding: '0.375rem 0.75rem',
    fontSize: '1rem',
    lineHeight: '1.5',
    borderRadius: ' 0.25rem',
  },
  spaces: ['2px', '4px', '6px', '8px', '16px', '32px'],
  input: {},
  productDetailsPage: {
    colors: {
      colorFont: 'white',
      bgSliderTwo: '#42c8cb',
      bgSliderOne: '#6bffc8',
      bgDotSlider: 'white',
      bgDotSliderActive: 'yellow',
      bgProductDetails: '#191919',
      bgAddToCart: '#dc0000',
      colorAddToCart: '#ffffff',
      bgAddedToCart: '#2fbf30',
      tickAddedToCart: '#146230',
      star: '#d0581c',
      starDeactive: '#bbb',
      discount: '#ffce00',
    },
    containerDetails: {
      margin: 'auto',
      width: '100%',
      maxWidth: '1200px',
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'stretch',
      media: {
        flexDirection: 'column',
      },
      productImage: {
        width: '100%',
        display: 'flex',
        flex: '1',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: '5px 0 0 5px',
        padding: ' 55px 0',
        width: '100%',
        margin: 'auto',
        position: 'relative',
      },
      productPic: {
        minWidth: '180px',
        maxWidth: '400px',
        position: 'relative',
        left: '0',
        margin: ' 40px 0',
        filter: ' drop-shadow(-6px 40px 23px rgba(black, 0.5))',
      },
      dots: {
        display: 'flex',
        alignContent: 'center',
        justifyContent: 'center',
        marginTop: '40px',
        a: {
          width: ' 10px',
          height: '10px',
          margin: '0 4px',
          borderRadius: '50%',
        },
        i: { display: 'none' },
      },
      productDetails: {
        borderRadius: ' 0 5px 5px 0',
        padding: '40px',
        display: 'flex',
        flexDirection: 'column',
        width: '100%',
        header: {
          marginBottom: '50px',
          position: 'relative',
          title: {
            textTransform: 'uppercase',
            margin: '0',
            fontWeight: 'bold',
          },
          price: {
            fontWeight: '700',
            marginTop: '5px',
            fontSize: '18px',
            current: {
              marginLeft: ' 6px',
            },
          },
          rate: {
            position: 'absolute',
            marginTop: '10px',
            top: '12px',
            right: '10px',
            a: {
              fontSize: '18px',
            },
          },
        },
        descriptionSec: {
          textAlign: 'justify',
        },
        buttonsBottom: {
          marginTop: 'auto',
        },
        addAndIncreaseButtons: {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
        },
        addToCartButton: {
          border: 'none',
          borderRadius: '4px',
          webkitBoxShadow: ' 0 3px 13px -2px rgba(0, 0, 0, 0.15)',
          boxShadow: ' 0 3px 13px -2px rgba(0, 0, 0, 0.15)',
          display: 'flex',
          justifyContent: 'space-around',
          minWidth: '165px',
          overflow: 'hidden',
          outline: 'none',
          padding: '0.7rem',
          position: 'relative',
          textTransform: 'uppercase',
          transition: '0.4s ease',
          width: 'auto',
          active: {
            webkitBoxShadow: '0 0 0 0.2rem rgba(252, 186, 3, 0.45)',
            boxShadow: '0 0 0 0.2rem rgba(252, 186, 3, 0.45)',
            webkitTransform: 'translateY(4px)',
            transform: 'translateY(4px)',
          },
          hover: {
            cursor: 'pointer',
          },
          focus: {
            webkitBoxShadow: ' 0 0 0 0.2rem rgba(255, 206, 0, 0.6)',
            boxShadow: '0 0 0 0.2rem rgba(255, 206, 0, 1)',
            webkitTransform: 'translateY(-1px)',
            transform: 'translateY(-1px)',
          },
          added: {
            webkitBoxShadow: '0 0 0 0.2rem rgba(11, 252, 3, 0.45)',
            boxShadow: '0 0 0 0.2rem rgba(11, 252, 3, 0.45)',
            addToCart: {
              display: 'none',
            },
            addedToCart: {
              display: 'block',
            },
            cartIcon: {
              animationDelay: ' 0.18s',
            },
            box: {
              top: '18px',
            },
            tik: {
              animationDelay: '0.7s',
            },
          },
        },
        addedToCart: {
          marginLeft: '36px',
        },
        addedToCart: {
          display: 'none',
          position: 'relative',
        },
        addToCartBox: {
          height: '5px',
          position: 'absolute',
          top: '0',
          width: '5px',
        },
        box: {
          transition: ' 0.4s ease',
          top: '-8px',
          box1: {
            left: '23px',
            transform: 'rotate(45deg)',
          },
          box2: {
            left: '32px',
            transform: 'rotate(63deg)',
          },
        },
        cartIcon: {
          left: '15px',
          position: 'absolute',
          top: '8px',
        },
        tick: {
          borderRadius: '50%',
          position: 'absolute',
          left: '28px',
          transform: 'scale(0)',
          top: '5px',
          zIndex: '2',
          visibility: 'hidden',
        },
        incDecSec: {
          display: 'inline-flex',
          outline: 'none',
          background: '#eee',
          borderRadius: '4px',
          overflow: 'hidden',
          padding: ' 0.32rem',
          incBtn: {
            width: '25px',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            color: 'black',
          },
          decBtn: {
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            width: '25px',
            color: 'black',
          },
          incDecInput: {
            width: '35px',
            border: 'none',
            webkitAppearance: 'none',
            textAlign: 'center',
            appearance: 'textfield',
            mozAppearance: 'textfield',
            margin: '0',
            fontWeight: 'bold',
            background: 'transparent',
          },
        },
      },
    },
  },
  login: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '80vh',
    backgroundColor: '#282828',
    color: '#d0d0d0',
    borderRadius: '24px',
    box: {
      backgroundImage: '/images/login/pexels-photo-2387793.jpg',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      alignContent: 'center',
      width: '320px',
      height: '450px',
      padding: '24px',
      borderRadius: '12px',
      boxShadow: '5px 8px 5px rgba(0, 0, 0, 0.3)',
      backgroundPosition: 'center',
      backgroundSize: 'cover',
      content: {
        textAlign: 'center',
        h2: {
          padding: '15px 0px 15px',
          fontSize: '2em',
          color: 'aliceblue',
          textTransform: 'uppercase',
          fontWeight: '700',
          letterSpacing: ' 2px',
        },
      },
      userInput: {
        position: 'relative',
        i: {
          position: 'absolute',
          right: '4px',
          top: '5px',
          padding: '9px 8px',
          color: '#848484',
          transition: '0.3s',
        },
      },
      passInput: {
        position: 'relative',
        i: {
          position: ' absolute',
          right: ' 4px',
          top: ' 5px',
          padding: ' 9px 8px',
          color: '#848484',
          transition: '0.3s',
        },
      },
      loginInput: {
        color: 'white',
        borderRadius: '2px',
        width: '240px',
        height: '20px',
        border: 'none',
        padding: '15px 20px',
        backgroundColor: 'rgba(65, 65, 65, 0.5)',
        marginBottom: '24px',
        focus: {
          outline: 'none',
          borderBottom: '2px solid #06ff8c',
          invalid: {
            borderBottom: '2px solid #ffce00',
          },
        },
      },
      loginBtn: {
        fontSize: '16px',
        fontWeight: '700',
        width: '240px',
        borderRadius: '44px',
        padding: '12px',
        backgroundColor: '#ffce00',
        border: 'none',
        cursor: 'pointer',
        marginBottom: '32px',
      },
      span: { color: '#ffce00' },
      newAccount: {
        color: '#c6a109',
        fontWeight: '400',
      },
      faPass: {
        color: '#626262',
        textDecoration: 'none',
      },
      hide1: {
        display: 'none',
      },
      logo: {
        position: 'absolute',
        top: '0',
        left: '0',
        width: 'auto',
        padding: '20px 20px',
        display: 'flex',
        justifyContent: ' space-between',
        alignItems: 'center',
      },
      logoImg: {
        position: 'relative',
        width: '78px',
        height: 'auto',
      },
    },
  },
  contact: {
    contactForm: {
      contactSection: {
        width: '70%',
        border: '1px solid #eee',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-around',
        margin: '0 auto',
        padding: '20px',
        media: {
          maxWidth: '960px',
          flexDirection: 'column',
          justifyContent: 'center',
        },
      },
      directionContact: {
        flex: '0.5',
        padding: '1.5rem',
        contactList: {
          listStyleType: 'none',
          paddingRight: '20px',
          listItem: {
            lineHeight: '4',
            color: '#aaa',
            svg: {
              marginRight: '20px',
            },
          },
          contactText: {
            fontSize: '18px',
            fontWeight: '300',
            letterSpacing: '1.9px',
            color: '#bbb',
          },
        },
        socialMediaList: {
          position: 'relative',
          fontSize: '22px',
          textAlign: 'center',
          width: '100%',
          margin: '0 auto',
          padding: '0',
          li: {
            position: 'relative',
            display: 'inline-block',
            height: '60px',
            width: '60px',
            margin: '10px 3px',
            lineHeight: '60px',
            borderRadius: '50%',
            color: '#fff',
            backgroundColor: 'rgb(27, 27, 27)',
            cursor: 'pointer',
            transition: 'all 0.5s ease-in-out',
            a: { color: '#fff' },
            after: {
              content: 'undefined',
              position: 'absolute',
              top: '0',
              left: '0',
              width: '60px',
              height: '60px',
              lineHeight: '60px',
              borderRadius: '50%',
              opacity: '0',
              boxShadow: '0 0 0 1px #fff',
              transition: 'all 0.2s ease-in-out',
            },
            hover: {
              backgroundColor: '#fff',
              a: { color: '#000' },
              after: {
                opacity: '1',
                transform: 'scale(1.12)',
                transitionTimingFunction:
                  'cubic-bezier(0.37, 0.74, 0.15, 1.65)',
              },
            },
          },
        },
      },
      formClass: {
        width: '100%',
        textAlign: 'left',
        button: {
          background: 'rgba(65, 65, 65, 0.5)',
          padding: '10px 30px',
          border: 'none',
          hover: {
            background: '#fff',
            color: 'black',
            transition: '1s',
          },
        },
      },
    },
  },
}

export default theme
